const Rest = [
    {
        id:1,
        title:"Murgh Tikka Masala",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:2,
        title:"Fish Moilee",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:3,
        title:"Safed Gosht",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:4,
        title:"French Toast Combo",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:5,
        title:"Chorizo & Egg Omelet",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:6,
        title:"Vegie Omelet",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"Mains",
},
    {
        id:7,
        title:"Banana Split",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"dessert",
},
    {
        id:8,
        title:"Sticky Toffee Pudding",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:180,
        category:"dessert",
},
    {
        id:9,
        title:"Pecan",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:150,
        category:"dessert",
},
    {
        id:10,
        title:"Apple Strudel",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:120,
        category:"dessert",
},
    {
        id:11,
        title:"Ice Cream Sundae",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:80,
        category:"dessert",
},
    {
        id:12,
        title:"Pancakes",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:100,
        category:"dessert",
},
    {
        id:13,
        title:"Spring Water",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},
    {
        id:14,
        title:"Coke, Diet Coke, Coke Zero",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},
    {
        id:15,
        title:"Orange Fanta",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},
    {
        id:16,
        title:"Lemonade, Lemon Squash",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},
    {
        id:17,
        title:"Sparkling Mineral Water",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},
    {
        id:18,
        title:"Soda Water",
        para:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt alias nihil itaque. Libero quam rerum voluptatibus optio fuga saepe ea?",
        price:200,
        category:"drinks",
},


]
export default Rest